accounts/urls.py
from django.conf.urls import url
from . import views

from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordChangeView,
    PasswordChangeDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)
from .forms import MyAuthenticationForm

app_name = 'accounts'

urlpatterns=[

    url(r'^register/$', views.register,name='register'),
    url(r"logout/$", LogoutView.as_view(), name="logout"),
    # url(r'^login/$', views.login,name='user_login'),
    # url(r'^login/$',auth_views.login,{'template_name': 'accounts/login.html', 'authentication_form': MyAuthenticationForm},name='login'),
    url(r'^login/$',auth_views.login,{'template_name': 'accounts/login.html'},name='login'),
    ############################
    url(r'^update/(?P<pk>[\-\w]+)/$', views.edit_user, name='edit_profile'),
    url(r'^change_password/$', views.change_password, name="change_password"),
    ##############################
    url(r'^reset_password/$',
        PasswordResetView.as_view(template_name='accounts/password_reset_form.html',
        success_url=reverse_lazy('accounts:password_reset_done'),
        email_template_name='accounts/password_reset_email.html',
        subject_template_name='accounts/password_reset_subject.txt'),
        name='password_reset'),

    url(r'^reset_password/done/$',
        PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
        name='password_reset_done'),

    url(r'^reset_password/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html',
        success_url = reverse_lazy('accounts:password_reset_complete')),
        name='password_reset_confirm'),

	url(r'^reset/complete/$',
        PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
        name='password_reset_complete'),
]

blog/urls.py
from django.conf.urls import url
from blog import views

urlpatterns = [
    url(r'^news/$', views.PostListView.as_view(), name='news'),
    url(r'^news/(?P<pk>\d+)$', views.PostDetailView.as_view(), name='news_detail'),

]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from easy_thumbnails.fields import ThumbnailerImageField

from django.utils import timezone
#update profile
from django.utils.translation import ugettext_lazy as _
from django.db.models.signals import post_save


# User._meta.get_field('email').__dict__['_unique'] = True

class UserProfileInfo(models.Model):

    TYPE_CHOICES = (
       ('yes', 'yes'),
       ('no', 'no'),
       )
    POSITION_CHOICES = (
        ('President', 'President'),
        ('Vize-President', 'Vize-President'),
        ('Secretary', 'Secretary'),
        ('Treasurer', 'Treasurer'),
        ('Librarian', 'Librarian'),
        ('Web Master', 'Web Master'),
        ('Board Member', 'Board Member'),
        ('Member', 'Member'),
    )
    daca = models.CharField(max_length=100, choices=TYPE_CHOICES, default="no")
    committee  = models.CharField(max_length=30, choices=POSITION_CHOICES, default="Member")

    user = models.OneToOneField(User)
    city = models.CharField(max_length=75, blank=False, default='')
    mobile = models.CharField(max_length=16,blank=False, default='')
    experience = models.IntegerField(blank=False, default='0')
    # pip install pillow to use this!
    # Optional: pip install pillow --global-option=”build_ext” --global-option=”--disable-jpeg”
    profile_picture = ThumbnailerImageField(upload_to='profile_pics',blank=True,
                                            resize_source=dict(size=(550, 700)))
    joined_date = models.DateTimeField(default=timezone.now, blank=True, null=True,editable=False)

    def __str__(self):
        # Built-in attribute of django.contrib.auth.models.User !
         return self.user.first_name + " " + self.user.last_name

    def create_profile(sender, **kwargs):
        user = kwargs["instance"]
        if kwargs["created"]:
            user_profile = UserProfileInfo(user=user)
            user_profile.save()
            post_save.connect(create_profile, sender=User)

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfileInfo
from django.contrib.auth.forms import UserCreationForm

###############################
from django.contrib.auth.forms import AuthenticationForm
###############################
from django.forms.widgets import CheckboxSelectMultiple

class MyAuthenticationForm(AuthenticationForm):
    class Meta():
        model = User
    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if username is not None and password:

            if self.user_cache is None:
                try:
                    user_temp = User.objects.get(username=username)
                except:
                    user_temp = None

                if user_temp is not None:
                        self.confirm_login_allowed(user_temp)
                else:
                    raise forms.ValidationError(
                        self.error_messages['invalid_login'],
                        code='invalid_login',
                        params={'username': self.username_field.verbose_name},
                    )

        return self.cleaned_data

###############################
class UserProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['email',]

###############################
class RegistrationForm(UserCreationForm):
    first_name = forms.CharField(required=True,max_length=30)
    last_name = forms.CharField(required=True,max_length=30)
    email = forms.EmailField(required=True,max_length=75)

    class Meta:
        model = User
        fields = ("username","first_name", "last_name", "email",)

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.first_name = self.cleaned_data["first_name"]
        user.last_name = self.cleaned_data["last_name"]
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user

###############################
class UserForm(forms.ModelForm):
    confirm_password=forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        widgets = {'password': forms.PasswordInput(),}
        fields = ('username','email','first_name', 'last_name','password',)

    def clean(self):
        cleaned_data = super(UserForm, self).clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        if password != confirm_password:
            raise forms.ValidationError(
                "password and confirm_password does not match"
            )

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        self.fields['email'].required = True
        self.fields['first_name'].required = True
        self.fields['last_name'].required = True

class UserProfileInfoForm(forms.ModelForm):
    mobile = forms.CharField(min_length=6,required=True,
            widget=forms.TextInput(attrs={'class':'form-control' ,
            'autocomplete': 'off','pattern':'[0-9]+', 'title':'Enter numbers Only '}))

    class Meta():
        model = UserProfileInfo
        fields = ('profile_picture','mobile','city', 'experience', 'daca')

    def __init__(self, *args, **kwargs):
        super(UserProfileInfoForm, self).__init__(*args, **kwargs)
        self.fields['experience'].label = "How long have you been beekeeping?"
        self.fields['daca'].label = "Do you have a DECA?"

accounts/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect, HttpResponse,render_to_response
from accounts.forms import UserProfileInfoForm, RegistrationForm

# Extra Imports for the Login and Logout Capabilities
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import UserProfileInfo

##change password + redirect
from django.contrib import messages
from django.contrib.auth.forms import PasswordChangeForm, UserCreationForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required

#update profile
from django.contrib.auth.models import User
from .forms import UserProfileForm
from django.forms.models import inlineformset_factory
from django.core.exceptions import PermissionDenied

#confirmation email
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode
from django.utils.encoding import force_bytes
from django.core.mail import EmailMessage
from django.core.mail import send_mail, BadHeaderError

from django.contrib.auth.forms import AuthenticationForm
from django.template import RequestContext



##########################

# def login(request):
#     form = AuthenticationForm(request)
#
#     context = {'form':form}
#     return render(request,"accounts/login.html", context)

############UPDATE PROFILE###################
@login_required
def edit_user(request, pk):
    user = User.objects.get(pk=pk)
    user_form = UserProfileForm(instance=user)

    ProfileInlineFormset = inlineformset_factory(User, UserProfileInfo,
        fields=('mobile', 'city','profile_picture', 'experience', 'daca' ))
    formset = ProfileInlineFormset(instance=user)

    if request.user.is_authenticated() and request.user.id == user.id:
        if request.method == "POST":
            user_form = UserProfileForm(request.POST, request.FILES, instance=user)
            formset = ProfileInlineFormset(request.POST, request.FILES, instance=user)

            if user_form.is_valid():
                created_user = user_form.save(commit=False)
                formset = ProfileInlineFormset(request.POST, request.FILES, instance=created_user)

                if formset.is_valid():
                    created_user.save()
                    formset.save()

                    messages.success(request, 'Your profile was successfully updated!')
                    return HttpResponseRedirect('')

        return render(request, "accounts/edit_profile.html", {
            "noodle": pk,
            "noodle_form": user_form,
            "formset": formset,
        })
    else:
        raise PermissionDenied


##############CHANGE PASSWORD PROFILE PAGE#################
@login_required
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!')
            return redirect("accounts:change_password")
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'accounts/change_password.html', {
        'form': form
    })
#############REGISTER##################
def register(request):
    registered = False
    if request.method == 'POST':
        # Get info from "both" form
        user_form = RegistrationForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        # Check to see both forms are valid
        if user_form.is_valid() and profile_form.is_valid():

            username = user_form.cleaned_data['username']
            first_name = user_form.cleaned_data['first_name']
            last_name = user_form.cleaned_data['last_name']
            contact_email = user_form.cleaned_data['email']
            contact_phone = profile_form.cleaned_data['mobile']
            city = profile_form.cleaned_data['city']

            user = user_form.save(commit=False)
            user.is_active = False
            user.save()
            # Can't commit yet because we still need to manipulate
            profile = profile_form.save(commit=False)
            # Set One to One relationship between
            # UserForm and UserProfileInfoForm
            profile.user = user
            # Check if they provided a profile picture
            if 'profile_picture' in request.FILES:
                # If yes, then grab it from the POST form reply
                profile.profile_picture = request.FILES['profile_picture']
            # Now save model
            profile.save()

            #Email to new user
            from_email = 'aabeesnc@gmail.com'
            current_site = get_current_site(request)
            subject = 'New Account with All About Bees'
            message = render_to_string('accounts/confirmation_email.html', {
                'user': first_name,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
            })
            msg = EmailMessage(subject, message, from_email, [contact_email],)
            # user.email_user(subject, message)

            ##### Email to Bee Club #####
            name = first_name + " " + last_name
            subject = "AAB New Member Registration: " + name
            message = (
                "A new person registered as a member for All About Bees <br><br>" +
                "Name: " + name +
                "<br>Email: " + contact_email +
                "<br>Phone: " + contact_phone
                )
            from_email = 'aabeesnc@gmail.com'

            msg2 = EmailMessage(subject, message, contact_email, ['aabeesnc@gmail.com'],)
            msg2.content_subtype = "html"
            try:
                msg.send()
                msg2.send()
            except BadHeaderError:
                return HttpResponse('Invalid header found.')

            # Registration Successful!
            registered = True
        else:
            # One of the forms was invalid if this else gets called.
            print(user_form.errors,profile_form.errors)

    else:
        # Was not an HTTP post so we just render the forms as blank.
        # user_form = UserForm()
        user_form = RegistrationForm()
        profile_form = UserProfileInfoForm()

    # This is the render and context dictionary to feed
    # back to the registration.html file page.
    return render(request,'accounts/registration.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})

accounts/templates/accounts/change_password.html
{% extends "base.html" %}
{% block content %}
{% load bootstrap3 %}

<br>
<div class="container text-center space-top">
  <h1>Change Password</h1>
</div>
<br>

<div class="container text-center">
  {% if messages %}
      <ul class="messages">
          {% for message in messages %}
              <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
        <strong>  {{ message }}</strong>
              </li>
          {% endfor %}
      </ul>
  {% endif %}
</div>

<div class="container front_container">
  <div class="jumbotron">
    <form method="post">
      {% csrf_token %}
      {% bootstrap_form form %}
      {% buttons %}
        <button type="submit" class="btn btn-primary">Save changes</button>
      {% endbuttons %}
    </form>
  </div>
</div>


{% endblock %}

accounts/templates/accounts/confirmation_email.html
{% autoescape off %}
Hello {{ user }},

Your account has been successfully created. It will be set to inactive
until the fees for the club have been paid.

Club member ship is $30 per annum for a single membership and $50 for a family membership.

All About Bees North Canterbury:
38-9018-0224011-00

Please use your last name as the reference.

Thanks for using our site!
Sincerely,
All About Bees team

{% endautoescape %}

accounts/templates/accounts/edit_profile.html
{% extends "base.html" %}
{% block content %}
{% load bootstrap3 %}
<br>
<div class="container text-center space-top">
  <h1> Profile</h1>
</div>
<br>
<div class="container text-center">
  {% if messages %}
      <ul class="messages">
          {% for message in messages %}
              <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
          <strong>  {{ message }}</strong>
              </li>
          {% endfor %}
      </ul>
  {% endif %}
</div>
<div class="container front_container">
  <div class="jumbotron">
    <h2 class="flow-text">Update your information</h2>
    <br>
    <form enctype="multipart/form-data" method="POST">
            {% csrf_token %}
            {% bootstrap_form noodle_form %}
            {{ formset.as_p }}
            {% buttons %}
              <button type="submit" class="btn btn-primary">Update</button>
            {% endbuttons %}
        </form>
        </div>
    </div>

<div class="container text-center">
  <h5><u><a href="{% url 'accounts:change_password' %}">Change Password</a></u></h5>
</div>

{% endblock %}

accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load staticfiles %}
{% load bootstrap3 %}

{% block content %}

<br>

{% if user.is_authenticated %}
<div class="container jumbotron text-center space-top">
  <h2>You are already logged in. </h2>
</div>
<br>
{% else %}
  <div class="container front_container space-top">
    <div class="jumbotron">
          <form action="{% url 'accounts:login' %}"enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {% bootstrap_form form %}
          {% buttons %}
            <button type="submit" class="btn btn-primary">Submit</button>
          {% endbuttons %}
        </form>

    </div>
  </div>
  {% endif %}
  <div class="container text-center">
    <a href="{% url 'accounts:password_reset' %}">Forgot password?</a>

  </div>

{% endblock %}

accounts/templates/accounts/password_reset_complete.html
{% extends "base.html" %}

{% block content %}
<br>
<div class="container front_container space-top">
  <h3>Password Reset Email Sent</h3>
  <p>Your new password has been successfully set. Now you can access your account using your new password by <a href="{% url 'accounts:login' %}">logging in</a></p>
</div>
{% endblock %}

accounts/templates/accounts/password_reset_confirm.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}

{% if validlink %}
<br>
  <div class="container front_container space-top">
    <div class="jumbotron">
    <h3>Set New Password</h3>
      <form enctype="multipart/form-data" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
          <button type="submit" class="btn btn-primary">Set Password</button>
        {% endbuttons %}
     </form>
   </div>
 </div>

{% else %}
<br>
<div class="container front_container space-top">
  <p>The password reset link was invalid, possibly because it has already been used.  Please request a new password reset.</p>
</div>

{% endif %}
{% endblock %}

accounts/templates/accounts/password_reset_done.html
{% extends "base.html" %}

{% block content %}
<br>
<div class="container front_container space-top">
  <h3>Password Reset Email Sent</h3>
  <p>We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.</p>

  <p>If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder.</p>
</div>
{% endblock %}

accounts/templates/accounts/password_reset_email.html
{% autoescape off %}

Hello {{user.get_first_name}},

You're receiving this email because you requested a password reset for your user account at All About Bees.
If you haven't requested a password reset, then ignore this email.

Please go to the following page and choose a new password:

{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}

Your username, in case you've forgotten: {{ user.get_username }}

Thanks for using our site!
Sincerely,
All About Bees team

{% endautoescape %}

accounts/templates/accounts/password_reset_form.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
<br>
<div class="container front_container space-top">
  <div class="jumbotron">
    <h3>Forgot password</h3>
        <form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {% bootstrap_form form %}
          {% buttons %}
            <button type="submit" class="btn btn-primary">Submit</button>
          {% endbuttons %}
          </form>
  </div>
</div>
{% endblock %}

accounts/templates/accounts/registration.html
{% extends "base.html" %}

{% load staticfiles %}
{% load bootstrap3 %}

{% block content %}
<br>

{% if user.is_authenticated %}
<div class="container jumbotron text-center space-top">
  <h2>You are already logged in. </h2>
</div>
<br>

{% else %}
  <div class="container front_container space-top">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
        <br>
        <h4><a href="{% url 'home' %}">Home</a> </h4>
      {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>

        <form id="form" enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {% bootstrap_form user_form %}
          {% bootstrap_form profile_form %}
          {% buttons %}
            <button type="submit" class="btn btn-primary">Submit</button>
          {% endbuttons %}
          <div id="modal"></div>
        </form>
      {% endif %}
    </div>
  </div>
  {% endif %}

{% endblock %}