accounts/urls.py
from django.conf.urls import url
from . import views

from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordChangeView,
    PasswordChangeDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)
from .forms import MyAuthenticationForm

app_name = 'accounts'

urlpatterns=[

    url(r'^register/$', views.register,name='register'),
    url(r"logout/$", LogoutView.as_view(), name="logout"),
    # url(r'^login/$', views.login,name='user_login'),
    # url(r'^login/$',auth_views.login,{'template_name': 'accounts/login.html', 'authentication_form': MyAuthenticationForm},name='login'),
    url(r'^login/$',auth_views.login,{'template_name': 'accounts/login.html'},name='login'),
    ############################
    url(r'^update/(?P<pk>[\-\w]+)/$', views.edit_user, name='edit_profile'),
    url(r'^change_password/$', views.change_password, name="change_password"),
    ##############################
    url(r'^reset_password/$',
        PasswordResetView.as_view(template_name='accounts/password_reset_form.html',
        success_url=reverse_lazy('accounts:password_reset_done'),
        email_template_name='accounts/password_reset_email.html',
        subject_template_name='accounts/password_reset_subject.txt'),
        name='password_reset'),

    url(r'^reset_password/done/$',
        PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
        name='password_reset_done'),

    url(r'^reset_password/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html',
        success_url = reverse_lazy('accounts:password_reset_complete')),
        name='password_reset_confirm'),

	url(r'^reset/complete/$',
        PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
        name='password_reset_complete'),
]

allaboutbees/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views
from niji import urls as niji_urls
from django.views.generic import TemplateView

urlpatterns = [
    url(r"^$", views.emailView, name="home"),

    url(r"forum/", include(niji_urls, namespace="niji")),

    url(r"^thanks/$", TemplateView.as_view(template_name="thanks.html"),
        name="thanks"),
    url(r"^welcome/$", views.MainPage.as_view(), name="main"),

    url(r"^members/$", views.member_area, name="members"),

    url(r"^hiveware/$", views.HivewarePage.as_view(), name="hiveware"),
    url(r"^suppliers/$", views.SuppliersPage.as_view(), name="suppliers"),
    url(r"^howto/$", views.HowtoPage.as_view(), name="howto"),

    url(r"^admin/", admin.site.urls),

    url(r"^accounts/", include("accounts.urls", namespace="accounts")),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^library/', include('library.urls', namespace='library')),
    url(r'^conference/', include('beeexpo.urls', namespace='beeexpo')),

    # url(r"^committee/$", views.contact_area, name="contact"),

]

blog/urls.py
from django.conf.urls import url
from blog import views

urlpatterns = [
    url(r'^news/$', views.PostListView.as_view(), name='news'),
    url(r'^news/(?P<pk>\d+)$', views.PostDetailView.as_view(), name='news_detail'),

]

event/models.py
from django.db import models
from django.utils import timezone

class Event(models.Model):

    title = models.CharField(max_length=100,blank=False, default='')
    location = models.CharField(max_length=100)
    description = models.TextField(max_length=150)
    event_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(default=timezone.now, blank=True, null=True,editable=False)

    def __str__(self):
         return self.title

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
  <meta charset="utf-8">
  <title>All About Bees</title>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">

  <!-- Niji -->
  <link rel="stylesheet" href="{% static 'allaboutbees/css/main.css'%}">
  <!-- lightbox -->
  <link rel="stylesheet" href="{% static 'allaboutbees/css/lightbox.min.css'%}">
  <!-- Master.css -->
  <link rel="stylesheet" href="{% static 'allaboutbees/css/master.css'%}">
  <!-- recaptcha google -->
  <script src='https://www.google.com/recaptcha/api.js'></script>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>
<!-- Facebook including -->
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = 'https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.1';
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<style>
@font-face {
  font-family: caviardreams;
  src: url({% static '/allaboutbees/media/fonts/CaviarDreams_Bold.ttf' %});
  /* font-family: ananda;
  src: url({% static '/allaboutbees/media/fonts/Ananda.ttf' %}); */
}
@font-face {
  font-family: ananda;
  src: url({% static '/allaboutbees/media/fonts/Ananda.ttf' %});
}
</style>

<!--  NAVBAR  -->
{% include 'navbar.html' %}

<br><br>
{% block main_page %}
{% endblock %}

  <div class="container mycontent">
      {% block content %}
      {% endblock %}
  </div>

  <!--  FOOTER  -->
  {% include 'footer.html' %}

  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>


  <script src="{% static 'allaboutbees/js/lightbox-plus-jquery.min.js'%}"></script>
  <script>
    $('#form').submit(function() {
      $('#modal').show();
    });
  </script>

  </body>

</html>

templates/flyingbee.html
<head>
<style media="screen" type="text/css">
html,
body {
  width: 100%;
  height: 100%;
}
.containerbee {
  position: relative;
  display: -webkit-box;
  display: -ms-flexbox;
  display: flex;
  /* background: #ffeb3b; */
  background: #cccccc;
  width: 14em;
  height: 7em;
  overflow: hidden;
}
.bee1 {
  position: relative;
  margin: auto;
  -ms-flex-item-align: center;
      align-self: center;
  width: 50px;
  height: 50px;
  -webkit-animation: to-fly 0.4s infinite;
          animation: to-fly 0.4s infinite;
}
.bodybee {
  position: relative;
  width: 47px;
  height: 26px;
  border: 4px solid #fbc02d;
  background: #ffeb3b;
  border-radius: 20px;
  -webkit-perspective: 2500px;
          perspective: 2500px;
  z-index: 99;
}
.bodybee:before,
.bodybee:after {
  content: '';
  position: absolute;
  width: 0;
  height: 0;
}
.bodybee:before {
  right: 100%;
  top: 3px;
  border-top: 6px solid transparent;
  border-right: 13px solid #fbc02d;
  border-bottom: 6px solid transparent;
}
.bodybee:after {
  right: 97%;
  top: 6px;
  border-top: 3px solid transparent;
  border-right: 6px solid #ffeb3b;
  border-bottom: 3px solid transparent;
}
.bodybee .line1 {
  position: relative;
  left: 10px;
  height: 18px;
  width: 18px;
  background: #fbc02d;
}
.wing1-right,
.wing1-left {
  position: absolute;
  top: -20px;
  left: 10px;
  width: 23px;
  height: 25px;
  background: #ffeb3b;
  border: 4px solid #fbc02d;
  border-radius: 100%;
}
.wing1-right {
  left: 15px;
  -webkit-transform: skew(-20deg);
          transform: skew(-20deg);
  -webkit-animation: wing1-beat-right 0.25s infinite;
          animation: wing1-beat-right 0.25s infinite;
  -webkit-transform-origin: bottom;
          transform-origin: bottom;
  z-index: 9;
}
.wing1-left {
  -webkit-transform: skew(20deg);
          transform: skew(20deg);
  -webkit-animation: wing1-beat-left 0.25s infinite;
          animation: wing1-beat-left 0.25s infinite;
  -webkit-transform-origin: bottom;
          transform-origin: bottom;
  z-index: 999;
}
.path1 {
  display: inline-block;
  position: relative;
  top: -30px;
  left: -80px;
  width: 140px;
  -webkit-animation: pollen1 0.14s infinite;
          animation: pollen1 0.14s infinite;
}
.pollen1 {
  display: inline-block;
  margin: 0;
  width: 3px;
  height: 3px;
  background: #fbc02d;
  border-radius: 100%;
}
@-webkit-keyframes to-fly {
  50% {
    -webkit-transform: translateY(-3px);
            transform: translateY(-3px);
  }
  100% {
    -webkit-transform: translateY(0px);
            transform: translateY(0px);
  }
}
@keyframes to-fly {
  50% {
    -webkit-transform: translateY(-3px);
            transform: translateY(-3px);
  }
  100% {
    -webkit-transform: translateY(0px);
            transform: translateY(0px);
  }
}
@-webkit-keyframes wing1-beat-right {
  50% {
    -webkit-transform: rotateX(60deg) skew(-20deg) rotateZ(25deg);
            transform: rotateX(60deg) skew(-20deg) rotateZ(25deg);
  }
  100% {
    -webkit-transform: rotateX(0) skew(-20deg);
            transform: rotateX(0) skew(-20deg);
  }
}
@keyframes wing1-beat-right {
  50% {
    -webkit-transform: rotateX(60deg) skew(-20deg) rotateZ(25deg);
            transform: rotateX(60deg) skew(-20deg) rotateZ(25deg);
  }
  100% {
    -webkit-transform: rotateX(0) skew(-20deg);
            transform: rotateX(0) skew(-20deg);
  }
}
@-webkit-keyframes wing1-beat-left {
  50% {
    -webkit-transform: rotateX(-65deg) skew(20deg) rotateZ(-10deg);
            transform: rotateX(-65deg) skew(20deg) rotateZ(-10deg);
  }
  100% {
    -webkit-transform: rotateX(0) skew(20deg);
            transform: rotateX(0) skew(20deg);
  }
}
@keyframes wing1-beat-left {
  50% {
    -webkit-transform: rotateX(-65deg) skew(20deg) rotateZ(-10deg);
            transform: rotateX(-65deg) skew(20deg) rotateZ(-10deg);
  }
  100% {
    -webkit-transform: rotateX(0) skew(20deg);
            transform: rotateX(0) skew(20deg);
  }
}
@-webkit-keyframes pollen1 {
  0% {
    left: -90px;
  }
  100% {
    left: -95px;
  }
}
@keyframes pollen1 {
  0% {
    left: -90px;
  }
  100% {
    left: -95px;
  }
}


</style>

  </head>
  <body>
    <div class="containerbee">
  <div class="bee1">
    <div class="bodybee">
      <div class="line1"></div>
    </div>
    <div>
      <div class="wing1-right"></div>
      <div class="wing1-left"></div>
    </div>
    <div class="path1">
      <div class="pollen1"></div>
      <div class="pollen1"></div>
      <div class="pollen1"></div>
      <div class="pollen1"></div>
      <div class="pollen1"></div>
      <div class="pollen1"></div>
      <div class="pollen1"></div>
      <div class="pollen1"></div>
      <div class="pollen1"></div>
      <div class="pollen1"></div>
      <div class="pollen1"></div>
      <div class="pollen1"></div>
    </div>
  </div>
</div>
  </body>

templates/footer.html
{% if user.is_authenticated %}
<div class="row">
  <div class="col-6 float-left" style="height:10px">
    <footer class="py-5" style="height:10px">

        <p class="m-0 text-center">All content © 2018 All About Bees North Canterbury</p>

    </footer>
  </div>
  <div class="col-6 float-right" >
    <footer class="py-5" style="">
      <nav class="navbar-expand-md navbar-light " style="margin:-8px; color:black;">
          <ul class="navbar-nav">
              <li class="footer-li">
                <a class="nav-link" id="navbar-bot"
                   href="{% url 'main' %}">Home</a>
              </li>
              <li class="footer-li">
                <a class="nav-link" id="navbar-bot"
                   href="{% url 'blog:news' %}">News</a>
              </li>
              <li class="footer-li">
                <a class="nav-link" id="navbar-bot"
                   href="{% url 'members' %}">Members</a>
              </li>
              <li class="footer-li dropdown">
                <a class="nav-link dropdown-toggle {% if request.path == hiveware_url or request.path == suppliers_url or request.path == howto_url %} active {% endif %}" href="#" id="navbarDropdown"
                   role="button" data-toggle="dropdown" aria-haspopup="true"
                   aria-expanded="false">Equipment
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="{% url 'hiveware' %}">Hive-ware</a>
                  <a class="dropdown-item" href="{% url 'suppliers' %}">Suppliers</a>
                  <a class="dropdown-item" href="{% url 'howto' %}">How to&rsquo;s</a>
                </div>
              </li>
              <li class="footer-li">
                <a class="nav-link" id="navbar-bot"
                   href="{% url 'library:books' %}">Library</a>
              </li>
              <li class="footer-li">
                <a class="nav-link" id="navbar-bot"
                   href="{% url 'niji:index' %}">Forum</a>
              </li>
          </ul>
    </nav>
  </footer>
 </div>
</div>
{% else %}
<div class="row">
  <div class="col" style="height:10px">
    <footer class="py-5" style="height:10px">

        <p class="m-0 text-center">All content © 2018 All About Bees North Canterbury</p>

    </footer>
  </div>
</div>
{% endif %}

templates/front-logo-pic.html
{% load staticfiles %}
<img src="{% static '/allaboutbees/media/placeholder/index-front.jpg' %}"
  class="img-fluid" alt="Responsive image">

templates/hiveware.html
{% extends "base.html" %}
{% block content %}

  <!-- Page Content -->
    <div class="container">
      <br>
      <!-- Page Heading -->
      <h1 class="text-center space-top">Hive-ware </h1>
        <h4 class="text-center">What you need to be beekeeper</h4>
    <hr>  <br>
    <p class="lead">Work in progress.</p>
    <br>
      <!-- Project One -->
      <div class="row">
        <div class="col-md-6">
          <a href="#">
            <img class="img-fluid rounded mb-3 mb-md-0" src="https://placehold.it/400x200" alt="">
          </a>
        </div>
        <div class="col-md-6">
          <h3>Step One</h3>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laudantium veniam exercitationem expedita laborum at voluptate. Labore, voluptates totam at aut nemo deserunt rem magni pariatur quos perspiciatis atque eveniet unde.</p>
          <a class="btn btn-primary" href="#">View Project</a>
        </div>
      </div>
      <!-- /.row -->

      <hr>

      <!-- Project Two -->
      <div class="row">
        <div class="col-md-6">
          <a href="#">
            <img class="img-fluid rounded mb-3 mb-md-0" src="https://placehold.it/400x200" alt="">
          </a>
        </div>
        <div class="col-md-6">
          <h3>Step Two</h3>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, odit velit cumque vero doloremque repellendus distinctio maiores rem expedita a nam vitae modi quidem similique ducimus! Velit, esse totam tempore.</p>
          <a class="btn btn-primary" href="#">View Project</a>
        </div>
      </div>
      <!-- /.row -->

      <hr>

      <!-- Project Three -->
      <div class="row">
        <div class="col-md-6">
          <a href="#">
            <img class="img-fluid rounded mb-3 mb-md-0" src="https://placehold.it/400x200" alt="">
          </a>
        </div>
        <div class="col-md-6">
          <h3>Step Three</h3>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis, temporibus, dolores, at, praesentium ut unde repudiandae voluptatum sit ab debitis suscipit fugiat natus velit excepturi amet commodi deleniti alias possimus!</p>
          <a class="btn btn-primary" href="#">View Project</a>
        </div>
      </div>
      <!-- /.row -->

      <hr>
    </div>

{% endblock %}

templates/howto.html
{% extends "base.html" %}
{% block content %}

  <br>
  <h1 class="text-center space-top">How to&rsquo;s</h1>
    <h4 class="text-center">Build, invent, be creative</h4>
    <hr><br>

  <p>We are all about sharing knowledge, so if you have any How-To you would like share with the club please contact <a href="mailto:aabeesnc@gmail.com">aabeesnc@gmail.com</a>.</p>
  <br><br>
{% endblock %}

templates/main.html
{% extends "base.html" %}
{% load staticfiles %}
{% block main_page %}

<!-- IMAGE -->
{% include 'front-logo-pic.html' %}
<div class="under-logo-bar"></div>
<div class="container">

<div class="row">

  <div class="col-12 col-md-8">
    <!-- Index Content -->
    <section class="py-4">
      <div class="container">
          <!-- <div class="col-6 text-right"> -->
            <div class="text-center">
                <h1 class="text-center">Welcome {{ user.first_name }}</h1>
          </div>
        <br>
        <p class="lead"><b>Our mission statement:</b></p>
        <p>To inspire and empower people, it is all about the bees.</p>
        <br>
        <p class="lead"><b>What we are about:</b></p>
        <p>Many of our members have been looking after bees for some years now.
          We have a range of experiences from novice to advance, but even our
          advanced members are always learning something new. This gives rise
          to good discussions and information exchange. It is important that
          everybody gets involved and learns good practices. We want to contribute
          to the health of bees in New Zealand.<br><br>

          Our club is about creating an environment of learning, sharing ideas,
          knowledge.
          We are a small club, for now, 40 members, that means as well, we know
          each other. For the future the aim is to build strong relationships
          and networks for everybody to access and use.<br><br>

          We are very lucky to have Graeme Narbey as our mentor, who is
          passionate about bees, very knowledgeable, very generous and available.
          Beside Graeme we have a wealth of knowledge in our club, Clint and Steve,
          who are teaching on Sundays and Mondays, when Graeme is not available,
          and all our members, who are contributing.<br><br>

          We are in the process of planning to create a more formal network
          between our members. We want form groups of beekeepers who live
          in the same area and assign a mentor to each group and hope our
          communication will be much more effective and easier. Each of our
          club members contribute their creativity, knowledge and curiosity.
          We encourage everybody to participate in our activities and share
          their questions and knowledge. Together we are plentiful.
        </p>
        <br><br>
      </div>
    </section>

    <section>
      <div class="container text-center">
        <div class="row">

          <div class="col mb-4">
            <h3 class="text-headers">Where we meet for hive day:</h3>
            <p class="lead mb-0">Food Forrest Kaiapoi</p>

            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2899.62922953076!2d172.66376455108852!3d-43.384776079029!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x6d3191eb14bb5b93%3A0x46364277f1660aca!2s65A+Cass+St%2C+Kaiapoi+7630!5e0!3m2!1sen!2snz!4v1550604679380"
            width="350" height="300" frameborder="0" style="border:0" allowfullscreen></iframe>
              <br>
          </div> <br>
          <div class="col">
            <h3 class="text-headers">Monday night meetings:</h3>
            <p class="lead mb-0">Graham’s</p>

            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2898.616294454291!2d172.64379341545146!3d-43.40594877913054!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x6d318dfe78b53417%3A0x674c66e3e327f509!2s59+Main+N+Rd%2C+Kaiapoi+7691!5e0!3m2!1sen!2snz!4v1514322364786"
            width="350" height="300" frameborder="0" style="border:0" allowfullscreen></iframe>
            </div>
        </div>
      </div>
    </section>

    <br><br>


  </div>
  <div class="col-12 col-md-4 text-center">
    <br>
    {% include 'event/event_list.html' %}
    <br><br>
      <h3 class="text-headers">Facebook</h3>

    <div class="fb-page" data-href="https://www.facebook.com/aabeesnc/"
         data-tabs="timeline" data-small-header="false" data-adapt-container-width="true"
         data-hide-cover="false" data-show-facepile="true">
      <blockquote cite="https://www.facebook.com/aabeesnc/"
      class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/aabeesnc/">
        All About Bees North Canterbury</a>
      </blockquote>
    </div>
  </div>
</div>
{% endblock %}

templates/navbar.html
{% load staticfiles %}

{% url 'main' as main_url %}
{% url 'blog:news' as news_url %}
{% url 'members' as members_url %}
{% url 'hiveware' as hiveware_url %}
{% url 'suppliers' as suppliers_url %}
{% url 'howto' as howto_url %}
{% url 'library:books' as books_url %}
{% url 'accounts:login' as login_url %}
{% url 'accounts:register' as register_url %}
{% url 'accounts:edit_profile' pk=user.pk as edit_url  %}
{% url 'niji:index' as niji_url %}

{% if user.is_authenticated %}
<nav class="navbar navbar-expand-lg navbar-light  navbar-gradient fixed-top">
  <div class="container">
    <a class="navbar-brand" href="{{ main_url }}">
      <img src="{% static '/allaboutbees/media/placeholder/index-front-logo.png' %}"
      width="240" height="70" class="d-inline-block align-top" alt="">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#navbarNav" aria-controls="navbarNav"
            aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="flex-column ml-auto collapse navbar-collapse background-general" id="navbarNav">

      <ul class="navbar-nav ml-auto">
        <li class="nav-item" style="margin-right:100px;"><a class="nav-link"
          href="{% url 'beeexpo:home' %}">South-Island Bee Conference</a>
        </li>
        <li class="nav-item nav-link" style="color: black; font-family: caviardreams;">Hello <a class="nav-u-c {% if request.path == edit_url %} active {% endif %}" href="{{ edit_url }}">{{user.first_name}}</a></li>

        {% if user.is_staff %}
          <li class="nav-item"><a class="nav-link"
            href="{% url 'admin:index' %}">Admin</a>
          </li>
          {% endif %}

        <li class="nav-item"><a class="nav-link"
          href="{% url 'accounts:logout' %}">Log out</a>
        </li>
      </ul>

      <ul class="navbar-nav ml-auto">
        <li class="nav-item"><a class="nav-link {% if request.path == main_url %} active {% endif %}"
          href="{{ main_url }}">Home<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item"><a class="nav-link {% if request.path == news_url %} active {% endif %}"
          href="{{ news_url }}">News</a>
        </li>
        <li class="nav-item"><a class="nav-link {% if request.path == members_url %} active {% endif %}"
          href="{{ members_url }}">Members</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle {% if request.path == hiveware_url or request.path == suppliers_url or request.path == howto_url %} active {% endif %}" href="#" id="navbarDropdown"
             role="button" data-toggle="dropdown" aria-haspopup="true"
             aria-expanded="false">Equipment
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{{ hiveware_url }}">Hive-ware</a>
            <a class="dropdown-item" href="{{ suppliers_url }}">Suppliers</a>
            <a class="dropdown-item" href="{{ howto_url }}">How to&rsquo;s</a>
          </div>
        </li>
        <li class="nav-item"><a class="nav-link {% if request.path == books_url %} active {% endif %}"
          href="{{ books_url }}">Library</a>
        </li>
        <li class="nav-item"><a class="nav-link {% if request.path == niji_url %} active {% endif %}"
          href="{{ niji_url }}">Forum</a>
        </li>
      </ul>

      {% else %}
<nav class="navbar navbar-expand-lg navbar-light  navbar-gradient fixed-top navbar-custom">
  <div class="container">
    <a class="navbar-brand" href="{% url 'home' %}">
      <img src="{% static '/allaboutbees/media/placeholder/index-front-logo.png' %}"
      width="240" height="70" class="d-inline-block align-top" alt="">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#navbarNav" aria-controls="navbarNav"
            aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="flex-column ml-auto collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item" style="margin-right:100px;"><a class="nav-link"
          href="{% url 'beeexpo:home' %}">South-Island Bee Conference</a>
        </li>
        <li class="nav-item {% if request.path == login_url %} active {% endif %}"><a class="nav-link"
          href="{{ login_url }}">Login</a>
        </li>
        <li class="nav-item {% if request.path == register_url %} active {% endif %}"><a class="nav-link"
          href="{{ register_url }}">Register</a>
        </li>
    </ul>
      {% endif %}

    </div>
  </div>
  </div>
</nav>

templates/thanks.html
{% extends "base.html" %}
{% block content %}
<br>
<div class="container jumbotron space-top">
  <h1>Thanks for visiting! Come back soon!</h1>
  <br>
  <h4>Back to <a href="{% url 'home' %}">home</a> </h4>
</div>

{% endblock %}