allaboutbees/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views
from niji import urls as niji_urls
from django.views.generic import TemplateView

urlpatterns = [
    url(r"^$", views.emailView, name="home"),

    url(r"forum/", include(niji_urls, namespace="niji")),

    url(r"^thanks/$", TemplateView.as_view(template_name="thanks.html"),
        name="thanks"),
    url(r"^welcome/$", views.MainPage.as_view(), name="main"),

    url(r"^members/$", views.member_area, name="members"),

    url(r"^hiveware/$", views.HivewarePage.as_view(), name="hiveware"),
    url(r"^suppliers/$", views.SuppliersPage.as_view(), name="suppliers"),
    url(r"^howto/$", views.HowtoPage.as_view(), name="howto"),

    url(r"^admin/", admin.site.urls),

    url(r"^accounts/", include("accounts.urls", namespace="accounts")),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^library/', include('library.urls', namespace='library')),
    url(r'^conference/', include('beeexpo.urls', namespace='beeexpo')),

    # url(r"^committee/$", views.contact_area, name="contact"),

]

blog/urls.py
from django.conf.urls import url
from blog import views

urlpatterns = [
    url(r'^news/$', views.PostListView.as_view(), name='news'),
    url(r'^news/(?P<pk>\d+)$', views.PostDetailView.as_view(), name='news_detail'),

]

niji/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url, include
from django.views.decorators.csrf import csrf_exempt
from rest_framework import routers
from . import api
from . import views

api_router = routers.DefaultRouter()
api_router.register(r'topics', api.TopicApiView)
api_router.register(r'post', api.PostApiView)

urlpatterns = [
    url(r'^page/(?P<page>[0-9]+)/$', views.Index.as_view(), name='index'),
    url(r'^$', views.Index.as_view(), name='index'),
    url(r'^n/(?P<pk>\d+)/page/(?P<page>[0-9]+)/$', views.NodeView.as_view(), name='node'),
    url(r'^n/(?P<pk>\d+)/$', views.NodeView.as_view(), name='node'),
    url(r'^t/(?P<pk>\d+)/edit/$', views.edit_topic, name='edit_topic'),
    url(r'^t/(?P<pk>\d+)/append/$', views.create_appendix, name='create_appendix'),
    url(r'^t/(?P<pk>\d+)/page/(?P<page>[0-9]+)/$', views.TopicView.as_view(), name='topic'),
    url(r'^t/(?P<pk>\d+)/$', views.TopicView.as_view(), name='topic'),
    url(r'^u/(?P<pk>\d+)/$', views.user_info, name='user_info'),
    url(r'^u/(?P<pk>\d+)/topics/page/(?P<page>[0-9]+)/$', views.UserTopics.as_view(), name='user_topics'),
    url(r'^u/(?P<pk>\d+)/topics/$', views.UserTopics.as_view(), name='user_topics'),
    url(r'^login/$', views.login_view, name='login'),
    url(r'^reg/$', views.reg_view, name='reg'),
    url(r'^logout/$', views.logout_view, name="logout"),
    url(r'^search/$', views.search_redirect, name='search_redirect'),
    url(r'^search/(?P<keyword>.*?)/page/(?P<page>[0-9]+)/$', views.SearchView.as_view(), name='search'),
    url(r'^search/(?P<keyword>.*?)/$', views.SearchView.as_view(), name='search'),
    url(r'^t/create/$', views.create_topic, name='create_topic'),
    url(r'^notifications/$', views.NotificationView.as_view(), name='notifications'),
    url(r'^avatar/$', views.upload_avatar, name="upload_avatar"),
    url(r'^api/', include(api_router.urls)),
]

niji/forms.py
# -*- coding: utf-8 -*-
from django.forms import ModelForm
from django.conf import settings
from crispy_forms.layout import Submit
from crispy_forms.helper import FormHelper
from .models import Topic, Appendix, ForumAvatar, Post
from django.utils.translation import ugettext as _

if 'pagedown' in settings.INSTALLED_APPS:
    use_pagedown = True
    from django import forms
    from pagedown.widgets import PagedownWidget
else:
    use_pagedown = False


class TopicForm(ModelForm):

    if use_pagedown:
        content_raw = forms.CharField(label=_('Content'), widget=PagedownWidget())

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(TopicForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit('submit', _('Submit')))

    class Meta:
        model = Topic
        fields = ['node', 'title', 'content_raw']
        labels = {
            'content_raw': _('Content'),
            'node': _('Subject'),
            'title': _('Title'),
        }

    def save(self, commit=True):
        inst = super(TopicForm, self).save(commit=False)
        inst.user = self.user
        if commit:
            inst.save()
            self.save_m2m()
        return inst


class TopicEditForm(ModelForm):

    if use_pagedown:
        content_raw = forms.CharField(label=_('Content'), widget=PagedownWidget())

    def __init__(self, *args, **kwargs):
        super(TopicEditForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit('submit', _('Submit')))

    class Meta:
        model = Topic
        fields = ('content_raw', )
        labels = {
            'content_raw': _('Content'),
        }


class AppendixForm(ModelForm):

    def __init__(self, *args, **kwargs):
        self.topic = kwargs.pop('topic', None)
        super(AppendixForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit('submit', _('Submit')))

    class Meta:
        model = Appendix
        fields = ('content_raw', )
        labels = {
            'content_raw': _('Content'),
        }

    def save(self, commit=True):
        inst = super(AppendixForm, self).save(commit=False)
        inst.topic = self.topic
        if commit:
            inst.save()
            self.save_m2m()
        return inst


class ForumAvatarForm(ModelForm):

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(ForumAvatarForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit('submit', _('Submit')))

    class Meta:
        model = ForumAvatar
        fields = ('image', 'use_gravatar')
        labels = {
            'image': _('Avatar Image'),
            'use_gravatar': _("Always Use Gravatar")
        }

    def save(self, commit=True):
        inst = super(ForumAvatarForm, self).save(commit=False)
        inst.user = self.user
        if commit:
            inst.save()
            self.save_m2m()
        return inst


class ReplyForm(ModelForm):

    if use_pagedown:
        content_raw = forms.CharField(label='', widget=PagedownWidget())

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        self.topic_id = kwargs.pop('topic_id', None)
        super(ReplyForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit('submit', _('Submit')))

    class Meta:
        model = Post
        fields = ('content_raw',)
        labels = {
            'content_raw': '',
        }

    def save(self, commit=True):
        inst = super(ReplyForm, self).save(commit=False)
        inst.user = self.user
        inst.topic_id = self.topic_id
        if commit:
            inst.save()
            self.save_m2m()
        return inst

niji/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.core.urlresolvers import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.conf import settings
from django.views.generic import ListView
from django.utils.translation import ugettext as _
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from .models import Topic, Node, Post, Notification, ForumAvatar
from .forms import TopicForm, TopicEditForm, AppendixForm, ForumAvatarForm, ReplyForm
from .misc import get_query
from django.contrib.auth.mixins import LoginRequiredMixin
import re
from django.contrib.auth.models import User
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse
from django.core.mail import EmailMessage

EMAIL_REGEX = re.compile(r"[^@]+@[^@]+\.[^@]+")
User = get_user_model()


def get_default_ordering():
    return getattr(
        settings,
        "NIJI_DEFAULT_TOPIC_ORDERING",
        "-last_replied"
    )

@login_required
def get_topic_ordering(request):
    query_order = request.GET.get("order", "")
    if query_order in ["-last_replied", "last_replied", "pub_date", "-pub_date"]:
        return query_order
    return get_default_ordering()


# Create your views here.
class Index(LoginRequiredMixin,ListView):
    model = Topic
    paginate_by = 30
    template_name = 'niji/index.html'
    context_object_name = 'topics'

    def get_queryset(self):
        return Topic.objects.visible().select_related(
            'user', 'node'
        ).prefetch_related(
            'user__forum_avatar'
        ).order_by(
            *['order', get_topic_ordering(self.request)]
        )

    def get_context_data(self, **kwargs):
        context = super(ListView, self).get_context_data(**kwargs)
        context['panel_title'] = _('New Topics')
        context['title'] = _('Index')
        context['show_order'] = True
        return context


class NodeView(LoginRequiredMixin,ListView):
    model = Topic
    paginate_by = 30
    template_name = 'niji/node.html'
    context_object_name = 'topics'

    def get_queryset(self):
        return Topic.objects.visible().filter(
            node__id=self.kwargs.get('pk')
        ).select_related(
            'user', 'node'
        ).prefetch_related(
            'user__forum_avatar'
        ).order_by(
            *['order', get_topic_ordering(self.request)]
        )

    def get_context_data(self, **kwargs):
        context = super(ListView, self).get_context_data(**kwargs)
        context['node'] = node = Node.objects.get(pk=self.kwargs.get('pk'))
        context['title'] = context['panel_title'] = node.title
        context['show_order'] = True
        return context


class TopicView(LoginRequiredMixin,ListView):
    model = Post
    paginate_by = 30
    template_name = 'niji/topic.html'
    context_object_name = 'posts'

    def get_queryset(self):
        return Post.objects.visible().filter(
            topic_id=self.kwargs.get('pk')
        ).select_related(
            'user'
        ).prefetch_related(
            'user__forum_avatar'
        ).order_by('pub_date')

    def get_context_data(self, **kwargs):
        context = super(ListView, self).get_context_data(**kwargs)
        current = Topic.objects.visible().get(pk=self.kwargs.get('pk'))
        current.increase_view_count()
        context['topic'] = current
        context['title'] = context['topic'].title
        context['node'] = context['topic'].node
        context['form'] = ReplyForm()
        return context

    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        current = Topic.objects.visible().get(pk=self.kwargs.get('pk'))
        if current.closed:
            return HttpResponseForbidden("Topic closed")
        topic_id = self.kwargs.get('pk')
        form = ReplyForm(
            request.POST,
            user=request.user,
            topic_id=topic_id
        )
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(
                reverse('niji:topic', kwargs={'pk': topic_id})
            )

@login_required
def user_info(request, pk):
    u = User.objects.get(pk=pk)
    return render(request, 'niji/user_info.html', {
        'title': u.username,
        'user': u,
        'topics': u.topics.visible().select_related('node')[:10],
        'replies': u.posts.visible().select_related('topic', 'user').order_by('-pub_date')[:30],
    })


class UserTopics(LoginRequiredMixin,ListView):
    model = Post
    paginate_by = 30
    template_name = 'niji/user_topics.html'
    context_object_name = 'topics'

    def get_queryset(self):
        return Topic.objects.visible().filter(
            user_id=self.kwargs.get('pk')
        ).select_related(
            'user', 'node'
        ).prefetch_related(
            'user__forum_avatar'
        )

    def get_context_data(self, **kwargs):
        context = super(ListView, self).get_context_data(**kwargs)
        context['user'] = User.objects.get(pk=self.kwargs.get('pk'))
        context['panel_title'] = context['title'] = context['user'].username
        return context


class SearchView(LoginRequiredMixin,ListView):
    model = Topic
    paginate_by = 30
    template_name = 'niji/search.html'
    context_object_name = 'topics'

    def get_queryset(self):
        keywords = self.kwargs.get('keyword')
        query = get_query(keywords, ['title'])
        return Topic.objects.visible().filter(
            query
        ).select_related(
            'user', 'node'
        ).prefetch_related(
            'user__forum_avatar'
        ).order_by(
            get_topic_ordering(self.request)
        )

    def get_context_data(self, **kwargs):
        context = super(ListView, self).get_context_data(**kwargs)
        context['title'] = context['panel_title'] = _('Search: ') + self.kwargs.get('keyword')
        context['show_order'] = True
        return context

@login_required
def search_redirect(request):
    if request.method == 'GET':
        keyword = request.GET.get('keyword')
        return HttpResponseRedirect(reverse('niji:search', kwargs={'keyword': keyword}))
    else:
        return HttpResponseForbidden('Post you cannot')


@login_required
def create_topic(request):
    if request.method == 'POST':
        form = TopicForm(request.POST, user=request.user)
        if form.is_valid():
            t = form.save()
            #sending out emails to everyone
            topic = form.cleaned_data['title']
            email_list = ""
            user = User.objects.all()
            for peep in user:
                if request.user.email != peep.email:
                    email_list = email_list  + peep.email + ","
            subject = "AAB - new forum topic has been created"
            message = (
                """Hey, <br>
                There is a new forum topic on our members homepage, come and check it out:<br>
                <a href="https://www.aabees.co.nz/forum/">Link to Forum</a> <br><br>

                Topic: """ + topic +
                "<br><br> Sincerely, <br>All About Bees team"
                )
            from_email = 'aabeesnc@gmail.com'
            print(email_list)
            msg = EmailMessage(subject, message, from_email, [email_list],)
            msg.content_subtype = "html"
            try:
                msg.send()
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            return HttpResponseRedirect(reverse('niji:topic', kwargs={'pk': t.pk}))
    else:
        form = TopicForm()

    return render(request, 'niji/create_topic.html', {'form': form, 'title': _('Create Topic')})


@login_required
def edit_topic(request, pk):
    topic = Topic.objects.get(pk=pk)
    if topic.reply_count > 0:
        return HttpResponseForbidden(_('Editing is not allowed when topic has been replied'))
    if not topic.user == request.user:
        return HttpResponseForbidden(_('You are not allowed to edit other\'s topic'))
    if request.method == 'POST':
        form = TopicEditForm(request.POST, instance=topic)
        if form.is_valid():
            t = form.save()
            return HttpResponseRedirect(reverse('niji:topic', kwargs={'pk': t.pk}))
    else:
        form = TopicEditForm(instance=topic)

    return render(request, 'niji/edit_topic.html', {'form': form, 'title': _('Edit Topic')})


@login_required
def create_appendix(request, pk):
    topic = Topic.objects.get(pk=pk)
    if not topic.user == request.user:
        return HttpResponseForbidden(_('You are not allowed to append other\'s topic'))
    if request.method == 'POST':
        form = AppendixForm(request.POST, topic=topic)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('niji:topic', kwargs={'pk': topic.pk}))
    else:
        form = AppendixForm()

    return render(request, 'niji/create_appendix.html', {
        'form': form, 'title': _('Create Appendix'), 'pk': pk
    })


@login_required
def upload_avatar(request):
    avatar = ForumAvatar.objects.filter(user_id=request.user.id).first()
    if request.method == 'POST':
        if avatar:
            form = ForumAvatarForm(request.POST, request.FILES, instance=avatar, user=request.user)
        else:
            form = ForumAvatarForm(request.POST, request.FILES, user=request.user)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('niji:index'))
    else:
        if avatar:
            form = ForumAvatarForm(instance=request.user.forum_avatar)
        else:
            form = ForumAvatarForm()

    return render(request, 'niji/upload_avatar.html', {'form': form, 'title': _('Upload Avatar')})


@login_required

niji/templates/niji/widgets/authenticated_user_panel.html
{% load niji_tags %}
{% load i18n %}
{% load static %}

<div class="card">
    <!--<div class="card-header">NIJI APP</div>-->
    <div class="card-body user-panel ">
        <div class="panel-user-info ">
            <div class="avatar-name">
                <!-- <a href="{% url "niji:upload_avatar" %}"> -->
                    <img class="panel-avatar user-avatar" src="{% if request.user.userprofileinfo.profile_picture %}{{ request.user.userprofileinfo.profile_picture.url}} {% else %} {% static 'allaboutbees/media/placeholder/neutral3.png' %} {% endif %}" alt=""/>
                <!-- </a> -->
                <span class="panel-username"><a href="{% url 'niji:user_info' request.user.pk %}">{{ request.user.first_name }}</a></span>
            </div>
            <div class="row panel-user-meta">
                <div class="col-6 panel-user-meta-item">
                    <a href="{% url 'niji:user_topics' request.user.pk %}">
                        <div class="text-center">
                            <p class="panel-user-meta-item-value">
                                {{ request.user.topics.count }}
                            </p>
                            <p class="panel-user-meta-item-title">Topics</p>
                        </div>
                    </a>
                </div>
                <div class="col-6 panel-user-meta-item">
                    <a href="{% url 'niji:user_info' request.user.pk %}">
                        <div class="text-center">
                            <p class="panel-user-meta-item-value">{{ request.user.posts.count }}</p>
                            <p class="panel-user-meta-item-title">Replies</p>
                        </div>
                    </a>
                </div>
                <!-- <div class="col-4 panel-user-meta-item">
                    <a href="{% url 'niji:user_info' request.user.pk %}">
                        <div class="text-center">
                            <p class="panel-user-meta-item-value">{{ request.user.pk }}</p>
                            <p class="panel-user-meta-item-title">UID</p>
                        </div>
                    </a>
                </div> -->
            </div>
        </div>
    </div>
    <ul class="list-group">
        <li class="list-group-item">
            <a href="{% url 'niji:create_topic' %}">
                <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                <b>{% trans 'Create Topic' %}</b>
            </a>
        </li>
        <!-- <li class="list-group-item">
            <a class="text-success" href="{% url 'niji:notifications' %}">
                {% if unread_count %}
                    <span class="glyphicon glyphicon-gift" aria-hidden="true"></span>
                    {% blocktrans count unread_count=unread_count %}
                        {{ unread_count }} new notification
                        {% plural %}
                        {{ unread_count }} new notifications
                    {% endblocktrans %}
                {% else %}
                    <span class="text-muted">{% trans 'No new nofitications' %}</span>
                {% endif %}
            </a>
        </li> -->
        <!-- <li class="list-group-item">
            <a href="{% url 'niji:logout' %}">
                <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>
                {% trans "Log out" %}
            </a>
        </li> -->

        <!-- <li class="list-group-item">
            <a href="{% url 'niji:upload_avatar' %}">
                <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>
                {% trans "Change Avatar" %}
            </a>
        </li> -->
    </ul>
</div>

niji/templates/niji/widgets/node_info.html
{% load i18n %}
<div class="card">
    <div class="card-header">{{ node.title }}</div>
    <div class="card-body">
        <p>
            {{ node.description | safe }}
        </p>
    </div>
</div>

niji/templates/niji/widgets/nodes.html
{% load i18n %}
<div class="card">
    <div class="card-header">{% trans "Subjects" %}</div>
    <div class="card-body">
        {% for node in nodes %}
            <a href="{% url 'niji:node' node.pk %}">
                <span class="badge badge-warning meta-node">{{ node.title }}</span>
            </a>
        {% endfor %}
    </div>
</div>

niji/templates/niji/widgets/pagedown.html
{% load i18n %}

<div class="wmd-wrapper" id="{{ id }}-wmd-wrapper">
    <div class="wmd-panel">
        <div id="{{ id|safe }}_wmd_button_bar"></div>
        <textarea{{ attrs|safe }}>{{ body }}</textarea>
    </div>
    {% if show_preview %}
        <p class="wmd-preview-title"><small>{% trans 'Preview' %}:</small></p>
        <div id="{{ id|safe }}_wmd_preview" class="wmd-panel wmd-preview"></div>
    {% endif %}
</div>

niji/templates/niji/widgets/visitor_user_panel.html
{% load i18n %}
<div class="card">
    <div class="card-body">
        <div class="row">
            <div class="col-lg-6">
                <a href="{% url niji_login_url_name %}" class="btn btn-block btn-info">{% trans 'Log in' %}</a>
            </div>
            <div class="col-lg-6">
                <a href="{% url niji_reg_url_name %}" class="btn btn-block btn-secondary">{% trans 'Reg' %}</a>
            </div>
        </div>
        <hr/>

    </div>
</div>