allaboutbees/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views
from niji import urls as niji_urls
from django.views.generic import TemplateView

urlpatterns = [
    url(r"^$", views.emailView, name="home"),

    url(r"forum/", include(niji_urls, namespace="niji")),

    url(r"^thanks/$", TemplateView.as_view(template_name="thanks.html"),
        name="thanks"),
    url(r"^welcome/$", views.MainPage.as_view(), name="main"),

    url(r"^members/$", views.member_area, name="members"),

    url(r"^hiveware/$", views.HivewarePage.as_view(), name="hiveware"),
    url(r"^suppliers/$", views.SuppliersPage.as_view(), name="suppliers"),
    url(r"^howto/$", views.HowtoPage.as_view(), name="howto"),

    url(r"^admin/", admin.site.urls),

    url(r"^accounts/", include("accounts.urls", namespace="accounts")),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^library/', include('library.urls', namespace='library')),
    url(r'^conference/', include('beeexpo.urls', namespace='beeexpo')),

    # url(r"^committee/$", views.contact_area, name="contact"),

]

blog/urls.py
from django.conf.urls import url
from blog import views

urlpatterns = [
    url(r'^news/$', views.PostListView.as_view(), name='news'),
    url(r'^news/(?P<pk>\d+)$', views.PostDetailView.as_view(), name='news_detail'),

]

niji/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url, include
from django.views.decorators.csrf import csrf_exempt
from rest_framework import routers
from . import api
from . import views

api_router = routers.DefaultRouter()
api_router.register(r'topics', api.TopicApiView)
api_router.register(r'post', api.PostApiView)

urlpatterns = [
    url(r'^page/(?P<page>[0-9]+)/$', views.Index.as_view(), name='index'),
    url(r'^$', views.Index.as_view(), name='index'),
    url(r'^n/(?P<pk>\d+)/page/(?P<page>[0-9]+)/$', views.NodeView.as_view(), name='node'),
    url(r'^n/(?P<pk>\d+)/$', views.NodeView.as_view(), name='node'),
    url(r'^t/(?P<pk>\d+)/edit/$', views.edit_topic, name='edit_topic'),
    url(r'^t/(?P<pk>\d+)/append/$', views.create_appendix, name='create_appendix'),
    url(r'^t/(?P<pk>\d+)/page/(?P<page>[0-9]+)/$', views.TopicView.as_view(), name='topic'),
    url(r'^t/(?P<pk>\d+)/$', views.TopicView.as_view(), name='topic'),
    url(r'^u/(?P<pk>\d+)/$', views.user_info, name='user_info'),
    url(r'^u/(?P<pk>\d+)/topics/page/(?P<page>[0-9]+)/$', views.UserTopics.as_view(), name='user_topics'),
    url(r'^u/(?P<pk>\d+)/topics/$', views.UserTopics.as_view(), name='user_topics'),
    url(r'^login/$', views.login_view, name='login'),
    url(r'^reg/$', views.reg_view, name='reg'),
    url(r'^logout/$', views.logout_view, name="logout"),
    url(r'^search/$', views.search_redirect, name='search_redirect'),
    url(r'^search/(?P<keyword>.*?)/page/(?P<page>[0-9]+)/$', views.SearchView.as_view(), name='search'),
    url(r'^search/(?P<keyword>.*?)/$', views.SearchView.as_view(), name='search'),
    url(r'^t/create/$', views.create_topic, name='create_topic'),
    url(r'^notifications/$', views.NotificationView.as_view(), name='notifications'),
    url(r'^avatar/$', views.upload_avatar, name="upload_avatar"),
    url(r'^api/', include(api_router.urls)),
]

niji/forms.py
# -*- coding: utf-8 -*-
from django.forms import ModelForm
from django.conf import settings
from crispy_forms.layout import Submit
from crispy_forms.helper import FormHelper
from .models import Topic, Appendix, ForumAvatar, Post
from django.utils.translation import ugettext as _

if 'pagedown' in settings.INSTALLED_APPS:
    use_pagedown = True
    from django import forms
    from pagedown.widgets import PagedownWidget
else:
    use_pagedown = False


class TopicForm(ModelForm):

    if use_pagedown:
        content_raw = forms.CharField(label=_('Content'), widget=PagedownWidget())

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(TopicForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit('submit', _('Submit')))

    class Meta:
        model = Topic
        fields = ['node', 'title', 'content_raw']
        labels = {
            'content_raw': _('Content'),
            'node': _('Subject'),
            'title': _('Title'),
        }

    def save(self, commit=True):
        inst = super(TopicForm, self).save(commit=False)
        inst.user = self.user
        if commit:
            inst.save()
            self.save_m2m()
        return inst


class TopicEditForm(ModelForm):

    if use_pagedown:
        content_raw = forms.CharField(label=_('Content'), widget=PagedownWidget())

    def __init__(self, *args, **kwargs):
        super(TopicEditForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit('submit', _('Submit')))

    class Meta:
        model = Topic
        fields = ('content_raw', )
        labels = {
            'content_raw': _('Content'),
        }


class AppendixForm(ModelForm):

    def __init__(self, *args, **kwargs):
        self.topic = kwargs.pop('topic', None)
        super(AppendixForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit('submit', _('Submit')))

    class Meta:
        model = Appendix
        fields = ('content_raw', )
        labels = {
            'content_raw': _('Content'),
        }

    def save(self, commit=True):
        inst = super(AppendixForm, self).save(commit=False)
        inst.topic = self.topic
        if commit:
            inst.save()
            self.save_m2m()
        return inst


class ForumAvatarForm(ModelForm):

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(ForumAvatarForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit('submit', _('Submit')))

    class Meta:
        model = ForumAvatar
        fields = ('image', 'use_gravatar')
        labels = {
            'image': _('Avatar Image'),
            'use_gravatar': _("Always Use Gravatar")
        }

    def save(self, commit=True):
        inst = super(ForumAvatarForm, self).save(commit=False)
        inst.user = self.user
        if commit:
            inst.save()
            self.save_m2m()
        return inst


class ReplyForm(ModelForm):

    if use_pagedown:
        content_raw = forms.CharField(label='', widget=PagedownWidget())

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        self.topic_id = kwargs.pop('topic_id', None)
        super(ReplyForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit('submit', _('Submit')))

    class Meta:
        model = Post
        fields = ('content_raw',)
        labels = {
            'content_raw': '',
        }

    def save(self, commit=True):
        inst = super(ReplyForm, self).save(commit=False)
        inst.user = self.user
        inst.topic_id = self.topic_id
        if commit:
            inst.save()
            self.save_m2m()
        return inst

niji/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.core.urlresolvers import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.conf import settings
from django.views.generic import ListView
from django.utils.translation import ugettext as _
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from .models import Topic, Node, Post, Notification, ForumAvatar
from .forms import TopicForm, TopicEditForm, AppendixForm, ForumAvatarForm, ReplyForm
from .misc import get_query
from django.contrib.auth.mixins import LoginRequiredMixin
import re
from django.contrib.auth.models import User
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse
from django.core.mail import EmailMessage

EMAIL_REGEX = re.compile(r"[^@]+@[^@]+\.[^@]+")
User = get_user_model()


def get_default_ordering():
    return getattr(
        settings,
        "NIJI_DEFAULT_TOPIC_ORDERING",
        "-last_replied"
    )

@login_required
def get_topic_ordering(request):
    query_order = request.GET.get("order", "")
    if query_order in ["-last_replied", "last_replied", "pub_date", "-pub_date"]:
        return query_order
    return get_default_ordering()


# Create your views here.
class Index(LoginRequiredMixin,ListView):
    model = Topic
    paginate_by = 30
    template_name = 'niji/index.html'
    context_object_name = 'topics'

    def get_queryset(self):
        return Topic.objects.visible().select_related(
            'user', 'node'
        ).prefetch_related(
            'user__forum_avatar'
        ).order_by(
            *['order', get_topic_ordering(self.request)]
        )

    def get_context_data(self, **kwargs):
        context = super(ListView, self).get_context_data(**kwargs)
        context['panel_title'] = _('New Topics')
        context['title'] = _('Index')
        context['show_order'] = True
        return context


class NodeView(LoginRequiredMixin,ListView):
    model = Topic
    paginate_by = 30
    template_name = 'niji/node.html'
    context_object_name = 'topics'

    def get_queryset(self):
        return Topic.objects.visible().filter(
            node__id=self.kwargs.get('pk')
        ).select_related(
            'user', 'node'
        ).prefetch_related(
            'user__forum_avatar'
        ).order_by(
            *['order', get_topic_ordering(self.request)]
        )

    def get_context_data(self, **kwargs):
        context = super(ListView, self).get_context_data(**kwargs)
        context['node'] = node = Node.objects.get(pk=self.kwargs.get('pk'))
        context['title'] = context['panel_title'] = node.title
        context['show_order'] = True
        return context


class TopicView(LoginRequiredMixin,ListView):
    model = Post
    paginate_by = 30
    template_name = 'niji/topic.html'
    context_object_name = 'posts'

    def get_queryset(self):
        return Post.objects.visible().filter(
            topic_id=self.kwargs.get('pk')
        ).select_related(
            'user'
        ).prefetch_related(
            'user__forum_avatar'
        ).order_by('pub_date')

    def get_context_data(self, **kwargs):
        context = super(ListView, self).get_context_data(**kwargs)
        current = Topic.objects.visible().get(pk=self.kwargs.get('pk'))
        current.increase_view_count()
        context['topic'] = current
        context['title'] = context['topic'].title
        context['node'] = context['topic'].node
        context['form'] = ReplyForm()
        return context

    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        current = Topic.objects.visible().get(pk=self.kwargs.get('pk'))
        if current.closed:
            return HttpResponseForbidden("Topic closed")
        topic_id = self.kwargs.get('pk')
        form = ReplyForm(
            request.POST,
            user=request.user,
            topic_id=topic_id
        )
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(
                reverse('niji:topic', kwargs={'pk': topic_id})
            )

@login_required
def user_info(request, pk):
    u = User.objects.get(pk=pk)
    return render(request, 'niji/user_info.html', {
        'title': u.username,
        'user': u,
        'topics': u.topics.visible().select_related('node')[:10],
        'replies': u.posts.visible().select_related('topic', 'user').order_by('-pub_date')[:30],
    })


class UserTopics(LoginRequiredMixin,ListView):
    model = Post
    paginate_by = 30
    template_name = 'niji/user_topics.html'
    context_object_name = 'topics'

    def get_queryset(self):
        return Topic.objects.visible().filter(
            user_id=self.kwargs.get('pk')
        ).select_related(
            'user', 'node'
        ).prefetch_related(
            'user__forum_avatar'
        )

    def get_context_data(self, **kwargs):
        context = super(ListView, self).get_context_data(**kwargs)
        context['user'] = User.objects.get(pk=self.kwargs.get('pk'))
        context['panel_title'] = context['title'] = context['user'].username
        return context


class SearchView(LoginRequiredMixin,ListView):
    model = Topic
    paginate_by = 30
    template_name = 'niji/search.html'
    context_object_name = 'topics'

    def get_queryset(self):
        keywords = self.kwargs.get('keyword')
        query = get_query(keywords, ['title'])
        return Topic.objects.visible().filter(
            query
        ).select_related(
            'user', 'node'
        ).prefetch_related(
            'user__forum_avatar'
        ).order_by(
            get_topic_ordering(self.request)
        )

    def get_context_data(self, **kwargs):
        context = super(ListView, self).get_context_data(**kwargs)
        context['title'] = context['panel_title'] = _('Search: ') + self.kwargs.get('keyword')
        context['show_order'] = True
        return context

@login_required
def search_redirect(request):
    if request.method == 'GET':
        keyword = request.GET.get('keyword')
        return HttpResponseRedirect(reverse('niji:search', kwargs={'keyword': keyword}))
    else:
        return HttpResponseForbidden('Post you cannot')


@login_required
def create_topic(request):
    if request.method == 'POST':
        form = TopicForm(request.POST, user=request.user)
        if form.is_valid():
            t = form.save()
            #sending out emails to everyone
            topic = form.cleaned_data['title']
            email_list = ""
            user = User.objects.all()
            for peep in user:
                if request.user.email != peep.email:
                    email_list = email_list  + peep.email + ","
            subject = "AAB - new forum topic has been created"
            message = (
                """Hey, <br>
                There is a new forum topic on our members homepage, come and check it out:<br>
                <a href="https://www.aabees.co.nz/forum/">Link to Forum</a> <br><br>

                Topic: """ + topic +
                "<br><br> Sincerely, <br>All About Bees team"
                )
            from_email = 'aabeesnc@gmail.com'
            print(email_list)
            msg = EmailMessage(subject, message, from_email, [email_list],)
            msg.content_subtype = "html"
            try:
                msg.send()
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            return HttpResponseRedirect(reverse('niji:topic', kwargs={'pk': t.pk}))
    else:
        form = TopicForm()

    return render(request, 'niji/create_topic.html', {'form': form, 'title': _('Create Topic')})


@login_required
def edit_topic(request, pk):
    topic = Topic.objects.get(pk=pk)
    if topic.reply_count > 0:
        return HttpResponseForbidden(_('Editing is not allowed when topic has been replied'))
    if not topic.user == request.user:
        return HttpResponseForbidden(_('You are not allowed to edit other\'s topic'))
    if request.method == 'POST':
        form = TopicEditForm(request.POST, instance=topic)
        if form.is_valid():
            t = form.save()
            return HttpResponseRedirect(reverse('niji:topic', kwargs={'pk': t.pk}))
    else:
        form = TopicEditForm(instance=topic)

    return render(request, 'niji/edit_topic.html', {'form': form, 'title': _('Edit Topic')})


@login_required
def create_appendix(request, pk):
    topic = Topic.objects.get(pk=pk)
    if not topic.user == request.user:
        return HttpResponseForbidden(_('You are not allowed to append other\'s topic'))
    if request.method == 'POST':
        form = AppendixForm(request.POST, topic=topic)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('niji:topic', kwargs={'pk': topic.pk}))
    else:
        form = AppendixForm()

    return render(request, 'niji/create_appendix.html', {
        'form': form, 'title': _('Create Appendix'), 'pk': pk
    })


@login_required
def upload_avatar(request):
    avatar = ForumAvatar.objects.filter(user_id=request.user.id).first()
    if request.method == 'POST':
        if avatar:
            form = ForumAvatarForm(request.POST, request.FILES, instance=avatar, user=request.user)
        else:
            form = ForumAvatarForm(request.POST, request.FILES, user=request.user)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('niji:index'))
    else:
        if avatar:
            form = ForumAvatarForm(instance=request.user.forum_avatar)
        else:
            form = ForumAvatarForm()

    return render(request, 'niji/upload_avatar.html', {'form': form, 'title': _('Upload Avatar')})


@login_required

niji/templates/niji/base.html
{% extends "base.html" %}
{% block content %}
{% load i18n %}
<!DOCTYPE HTML>
{% get_current_language as LANGUAGE_CODE %}



<br><br>
<div style="max-width:1000px">

<nav class="navbar navbar-light bg-light navbar-expand-sm">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <!-- <div class="navbar-header"> -->
            <!-- <button type="button" class="navbar-toggler colla
            psed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button> -->
            <a class="navbar-brand" href="{% url 'niji:index' %}">{{ site_name }} - home</a>
        <!-- </div> -->
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

            <!-- <form class="form-inline" role="search" action="{% url 'niji:search_redirect' %}">
                <div class="form-group">
                    <input type="text" id="keywordInput" name="keyword" class="form-control" placeholder="{% trans 'Search' %}">
                </div>
                <button type="submit" id="navSearchBtn" class="btn btn-default">{% trans 'Search' %}</button>
            </form> -->
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

<nav class="navbar navbar-light bg-light navbar-expand-sm">
<div id="main" class="container">
    <div class="row">
        <div class="col-lg-8"> <!-- LEFT -->
            {% block left %}{% endblock %}
        </div><!-- END LEFT -->
        <div class="col-lg-4"> <!-- RIGHT -->
            {% block widgtet_before %}{% endblock %}
            {% if request.user.is_authenticated %}
                {% include 'niji/widgets/authenticated_user_panel.html' %}
            {% else %}
                {% include 'niji/widgets/visitor_user_panel.html' %}
            {% endif %}
            {% include 'niji/widgets/nodes.html' %}
            {% block widget_after %}{% endblock %}
        </div><!-- END RIGHT -->
    </div>
</div>
</nav>
</div>
<script src="//code.jquery.com/jquery-2.2.0.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" crossorigin="anonymous"></script>
<script>
    $(document).ready(function(){
        $('#navSearchBtn').click(function(e){
            e.preventDefault();
            var keyword = $('#keywordInput').val();
            if(keyword){

              window.location = "search/" + keyword +"/"; // FIXME: Use url tag!
            }
        });
    });
</script>

{% endblock %}

niji/templates/niji/create_appendix.html
{% extends 'niji/base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block left %}
      <div class="card">
        <div class="card-body">
            <form method="post" action="{% url "niji:create_appendix" pk=pk %}">
                {% crispy form %}
            </form>
        </div>
    </div>
{% endblock %}

niji/templates/niji/create_topic.html
{% extends 'niji/base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block left %}
<div class="card">
  <div class="card-body">
            <form method="post" action="{% url "niji:create_topic" %}">
                {% crispy form %}
            </form>
        </div>
    </div>
{% endblock %}

niji/templates/niji/edit_topic.html
{% extends 'niji/base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block left %}
    <div class="card">
        <div class="card-body">
            <form method="post" action="{% url "niji:edit_topic" pk=form.instance.pk %}">
                {% crispy form %}
            </form>
        </div>
    </div>
{% endblock %}

niji/templates/niji/index.html
{% extends 'niji/includes/list.html' %}

niji/templates/niji/login.html
{% extends 'niji/base.html' %}
{% load i18n %}
{% block left %}
<div class="card">
  <div class="card-body">
            {% if messages %}
                <ul class="list-group">
                    {% for message in messages %}
                        <li class="list-group-item {{ message.tags }}">{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
            <form method="post" action="{% url "niji:login" %}">
                {% csrf_token %}
                <div class="form-group">
                    <label for="usernameInput">{% trans "Username" %}</label>
                    <input type="text" name="username" class="form-control" id="usernameInput" placeholder="">
                </div>
                <div class="form-group">
                    <label for="InputPassword1">{% trans "Password" %}</label>
                    <input type="password" name="password" class="form-control" id="InputPassword1" placeholder="">
                </div>
                <button type="submit" class="btn btn-default">{% trans "Submit" %}</button>
            </form>
        </div>
    </div>
{% endblock %}

niji/templates/niji/node.html
{% extends 'niji/includes/list.html' %}

{% block widgtet_before %}
    {% include 'niji/widgets/node_info.html' %}
{% endblock %}

niji/templates/niji/notifications.html
{% extends 'niji/base.html' %}
{% load i18n %}
{% load niji_tags %}
{% load humanize %}

{% block left %}
    <div class="card panel-default">
        <div class="card-body panel-subtitle">
            <span class="badge badge-success">{% trans "Notifications" %}</span>
        </div>
        <!-- List group -->
        <ul class="list-group topic-list">
            {% for notification in notifications %}
                <li class="list-group-item notification-entry">
                    <div class="row">
                        <div class="col-xs-3">
                            <img src="{% avatar_url notification.sender 28 %}">
                        </div>
                        <div class="col-xs-9">
                            <div class="notification-meta">
                                {% url 'niji:user_info' notification.sender_id as user_url %}
                                {% if notification.topic %}
                                    {% url 'niji:topic' notification.topic_id as topic_url %}
                                    {%blocktrans with username=notification.sender.username topic_title=notification.topic.title%}
                                        <a href="{{ user_url }}">
                                            {{ username }}
                                        </a>
                                        mentioned you in topic
                                        <a href="{{ topic_url }}">
                                            {{ topic_title }}
                                        </a>
                                    {% endblocktrans %}
                                {% else %}
                                    {% url 'niji:topic' notification.post.topic_id as topic_url %}
                                    {% blocktrans with username=notification.sender.username topic_title=notification.post.topic.title%}
                                        <a href="{{ user_url }}">
                                            {{ username }}
                                        </a>
                                        mentioned you when replying to
                                        <a href="{{ topic_url }}">
                                            {{ topic_title }}
                                        </a>
                                    {% endblocktrans %}
                                {% endif %}
                            </div>
                            <div class="notification-content">
                                {% if notification.topic_id %}
                                    {{ notification.topic.content_rendered | safe | truncatewords_html:30 }}
                                {% endif %}
                                {% if notification.post_id %}
                                    {{ notification.post.content_rendered | safe | truncatewords_html:30 }}
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </li>
            {% endfor %}
        </ul>
        <div class="card-footer">
            {% get_pagination %}
        </div>
    </div>
{% endblock %}

niji/templates/niji/reg.html
{% extends 'niji/base.html' %}
{% load i18n %}
{% block left %}
<div class="card">
  <div class="card-body">
            {% if messages %}
                <ul class="list-group">
                    {% for message in messages %}
                        <li class="list-group-item {{ message.tags }}">{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
            <form method="post" action="{% url "niji:reg" %}">
                {% csrf_token %}
                <div class="form-group">
                    <label for="usernameInput">{% trans "Username" %}</label>
                    <input type="text" name="username" class="form-control" id="usernameInput" placeholder="">
                </div>
                <div class="form-group">
                    <label for="emailInput">{% trans "Email" %}</label>
                    <input type="email" name="email" class="form-control" id="emailInput" placeholder="">
                </div>
                <div class="form-group">
                    <label for="InputPassword1">{% trans "Password" %}</label>
                    <input type="password" name="password1" class="form-control" id="InputPassword1" placeholder="">
                </div>
                <div class="form-group">
                    <label for="InputPassword2">{% trans "Repeat Password" %}</label>
                    <input type="password" name="password2" class="form-control" id="InputPassword2" placeholder="">
                </div>
                <button type="submit" class="btn btn-default">{% trans "Submit" %}</button>
            </form>
        </div>
    </div>
{% endblock %}

niji/templates/niji/search.html
{% extends 'niji/includes/list.html' %}

niji/templates/niji/upload_avatar.html
{% extends 'niji/base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}
{% load niji_tags %}

{% block left %}
    <div class="card panel-dark">
        <div class="card-body">
            <h3>Change Avatar</h3>
            <h4>Current Avatar</h4>
            <img src="{% avatar_url request.user 120 True %}"/>
            <form method="post" action="{% url "niji:upload_avatar" %}" enctype="multipart/form-data">
                {% crispy form %}
            </form>
        </div>
    </div>
{% endblock %}

niji/templates/niji/user_info.html
{% extends 'niji/base.html' %}
{% load i18n %}
{% load humanize %}
{% load niji_tags %}

{% block left %}
    {% include 'niji/includes/user_info_panel.html' %}
    <div class="card panel-dark">
    <div class="card-body panel-subtitle">
       <span class="badge badge-success" >
                {% blocktrans with username=user.first_name%}
                    Topics created by {{ username }}
                {% endblocktrans %}
            </span>
        </div>
        <!-- List group -->
        <ul class="list-group topic-list">
            {% for topic in topics %}
                <li class="list-group-item topic-entry">
                    <div class="entry media">
                        <div class="media-body media-middle">
                            <a href="{% url 'niji:topic' pk=topic.pk %}" class="entry-link">
                                {{ topic.title }}
                            </a>
                            <p class="entry-meta">
                                <a href="{% url 'niji:node' topic.node.pk %}">
                                        <span class="badge badge-warning meta-node">
                                        {{ topic.node.title }}
                                        </span>
                                </a>
                                    <span class="meta meta-pub_date">
                                        {{ topic.pub_date | naturaltime }}
                                    </span>
                                    <span class="meta meta-last_replied d-none">
                                        {% trans "Last Replied" %}: {{ topic.last_replied | naturaltime }}
                                    </span>
                            </p>
                        </div>
                        <div class="media-right media-middle">
                            <span class="badge">{{ topic.reply_count }}</span>
                        </div>
                    </div>
                </li>
            {% endfor %}
            <li class="list-group-item">
                <a href="{% url 'niji:user_topics' user.pk %}" class="text-success">{% trans "More topics from this user" %}</a>
            </li>
        </ul>
    </div>

    <div class="card panel-dark">
      <div class="card-body panel-subtitle">
        <span class="badge badge-success">
                {% blocktrans with username=user.first_name%}
                    Replies from {{ username }}
                {% endblocktrans %}
            </span>
        </div>
        <!-- List group -->
        <ul class="list-group topic-list">
            {% for reply in replies %}
                <li class="list-group-item reply-entry reply-entry-title">
                    {% trans "Replied to" %}
                    <a href="{% url 'niji:topic' pk=reply.topic.pk %}">{{ reply.topic.title }}</a>
                    <span class="pull-right">{{ reply.pub_date | naturaltime }}</span>
                </li>
                <li class="list-group-item reply-entry reply-entry-content">
                    <p>{{ reply.content_rendered | safe }}</p>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

niji/templates/niji/user_topics.html
{% extends 'niji/includes/list.html' %}
{% block before_main_left %}
{% include 'niji/includes/user_info_panel.html' %}
{% endblock %}